### ISSUE TITLE
Object stacking

### ISSUE THREAD

**Issue by kionell** [minetoblend/osu-cad#1]
Hey, just wanted to say that you can use [osu-standard-stable](https://github.com/kionell/osu-standard-stable) for osu!standard related stuff. This includes [object stacking](https://github.com/kionell/osu-standard-stable/blob/master/src/Beatmaps/StandardBeatmapProcessor.ts) as well. I'm sorry if it wasn't clear from the start. 
However, I must warn that additional conversion from the plain Beatmap object to the beatmap with applied ruleset takes more time, especially for beatmaps with very complex slider geometry. This process with beatmap conversion is simillar to the osu! lazer tho.
At the very least if you need to implement real time object stacking, you can use my source code for it.

**Comment by minetoblend** [comment]
Closing this as stacking is now supported
